stages:
  - build

build-back:
  image: registry.gitlab.inria.fr/diverse/docker/docker-image/insa-maven:3.9.8-eclipse-temurin-21
  stage: build
  script:
    - cd backend
    - mvn clean package spring-boot:repackage
  artifacts:
    paths:
      - backend/target/site/jacoco/jacoco.xml
      - backend/target/backend-0.0.1.jar
    expire_in: 1 hour

build-front:
  image: registry.gitlab.inria.fr/diverse/docker/docker-image/insa-node:20.14.0
  stage: build
  cache:
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm install
    #- npm run ng lint && npm run ng build -- --configuration production --build-optimizer
    - npm run ng build -- --configuration production
  artifacts:
    paths:
      - frontend/dist/frontend/
    expire_in: 1 hour

