version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
